CREATE TABLE users (
    USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(120) NOT NULL,
    DEPOSIT  INTEGER DEFAULT 0 NOT NULL,
    ENABLED  BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE authorities (
    USERNAME    VARCHAR(50) NOT NULL,
    AUTHORITY   VARCHAR(50) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
);

CREATE TABLE product (
  ID                 INTEGER AUTO_INCREMENT PRIMARY KEY,
  AMOUNT_AVAILABLE   INTEGER NOT NULL,
  COST               INTEGER NOT NULL,
  PRODUCT_NAME       VARCHAR(255) NOT NULL,
  SELLER_NAME        VARCHAR(255) NOT NULL,
  FOREIGN KEY (SELLER_NAME) REFERENCES USERS (USERNAME)
);